disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- identifier_name
- multiple_closures_with_trailing_closure

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
